/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;
import Form.Laporan;

/**
 *
 * @author khoirul umam
 */
public class Beranda extends javax.swing.JFrame {

    Double totalAmount=0.0;
    Double cash=0.0;
    Double balance=0.0;
    Double bHeight=1.50;

    ArrayList<String> menuAry = new ArrayList<>();
    ArrayList<String> qtyAry = new ArrayList<>();
    ArrayList<String> hargaAry = new ArrayList<>();
    ArrayList<String> jumlahAry = new ArrayList<>();
    public PreparedStatement ps;
    public ResultSet rs;
    Connection conn = Config.Koneksi.koneksiDB();
    NumberFormat angkakoma = NumberFormat.getIntegerInstance();
    
    public Beranda() {
        initComponents();
        showDataItem();
        tampilTanggal();
        noFaktur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        item = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_Cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Menu = new javax.swing.JTable();
        transaksi = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txt_Menu = new javax.swing.JTextField();
        txt_Harga = new javax.swing.JTextField();
        btn_Add = new javax.swing.JButton();
        btn_Reset = new javax.swing.JButton();
        txt_Qty = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Transaksi = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_TotalBayar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Tunai = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Kembali = new javax.swing.JTextField();
        btn_Bayar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btn_TambahItem = new javax.swing.JButton();
        btn_Deposit = new javax.swing.JButton();
        btn_Pengeluaran = new javax.swing.JButton();
        btn_Laporan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lbl_Faktur = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_Tanggal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(0, 0, 0));

        Header.setBackground(new java.awt.Color(0, 51, 102));

        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setText("KASIR KEDAI KOPI NIKMAT");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(531, 531, 531))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        item.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cari Item");

        txt_Cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_CariKeyReleased(evt);
            }
        });

        tbl_Menu.setForeground(new java.awt.Color(255, 51, 0));
        tbl_Menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kategori", "Menu", "Harga"
            }
        ));
        tbl_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_MenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Menu);

        javax.swing.GroupLayout itemLayout = new javax.swing.GroupLayout(item);
        item.setLayout(itemLayout);
        itemLayout.setHorizontalGroup(
            itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        itemLayout.setVerticalGroup(
            itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(itemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        transaksi.setBackground(new java.awt.Color(0, 51, 102));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        txt_Menu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_Menu.setForeground(new java.awt.Color(0, 153, 0));
        txt_Menu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MenuActionPerformed(evt);
            }
        });

        txt_Harga.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_Harga.setForeground(new java.awt.Color(0, 153, 0));
        txt_Harga.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btn_Add.setBackground(new java.awt.Color(0, 153, 0));
        btn_Add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Add.setText("Add");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        btn_Reset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Reset.setText("Reset");
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });

        txt_Qty.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_Qty.setForeground(new java.awt.Color(0, 153, 0));
        txt_Qty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_QtyActionPerformed(evt);
            }
        });
        txt_Qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_QtyKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_Menu)
                .addGap(18, 18, 18)
                .addComponent(txt_Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_Qty, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Reset)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_Harga)
                        .addComponent(txt_Qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Add)
                            .addComponent(btn_Reset))
                        .addContainerGap())
                    .addComponent(txt_Menu)))
        );

        tbl_Transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Faktur", "Tanggal", "Menu", "Quantity", "Harga", "Jumlah"
            }
        ));
        tbl_Transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_TransaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_Transaksi);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Bayar");

        txt_TotalBayar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_TotalBayar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_TotalBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TotalBayarKeyReleased(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cash");

        txt_Tunai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_Tunai.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Tunai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_TunaiKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_TunaiKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_TunaiKeyTyped(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kembali");

        txt_Kembali.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_Kembali.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btn_Bayar.setBackground(new java.awt.Color(255, 102, 0));
        btn_Bayar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Bayar.setText("BAYAR");
        btn_Bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_TotalBayar)
                    .addComponent(txt_Tunai)
                    .addComponent(txt_Kembali)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btn_Bayar)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_TotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Tunai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btn_Bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 255));

        btn_TambahItem.setText("Tambah Item");
        btn_TambahItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TambahItemActionPerformed(evt);
            }
        });

        btn_Deposit.setText("Deposit");
        btn_Deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DepositActionPerformed(evt);
            }
        });

        btn_Pengeluaran.setText("Pengeluaran");
        btn_Pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PengeluaranActionPerformed(evt);
            }
        });

        btn_Laporan.setText("Laporan");
        btn_Laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btn_TambahItem)
                .addGap(18, 18, 18)
                .addComponent(btn_Deposit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Pengeluaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_TambahItem)
                    .addComponent(btn_Deposit)
                    .addComponent(btn_Pengeluaran)
                    .addComponent(btn_Laporan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("No. Faktur");

        lbl_Faktur.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Faktur.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Faktur.setForeground(new java.awt.Color(255, 153, 0));
        lbl_Faktur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Faktur.setText("Faktur");
        lbl_Faktur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tanggal");

        lbl_Tanggal.setBackground(new java.awt.Color(255, 255, 255));
        lbl_Tanggal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Tanggal.setForeground(new java.awt.Color(255, 153, 0));
        lbl_Tanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Tanggal.setText("Tgl Hari Ini");
        lbl_Tanggal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout transaksiLayout = new javax.swing.GroupLayout(transaksi);
        transaksi.setLayout(transaksiLayout);
        transaksiLayout.setHorizontalGroup(
            transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(transaksiLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(transaksiLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_Faktur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_Tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        transaksiLayout.setVerticalGroup(
            transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transaksiLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Faktur, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(transaksiLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MenuActionPerformed

    private void btn_BayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BayarActionPerformed
        // 1. Validasi Pembayaran
    if (txt_Kembali.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Maaf, Anda belum memasukkan pembayaran!", "Validasi", JOptionPane.WARNING_MESSAGE);
        return; 
    }

    DefaultTableModel model = (DefaultTableModel) tbl_Transaksi.getModel();

    try {
        // 2. Query Insert Database
        String sql = "INSERT INTO tbl_penjualan (no_faktur, tanggal, item, qty, harga, jumlah) VALUES (?, ?, ?, ?, ?, ?)";
        ps = conn.prepareStatement(sql);

        // Bersihkan data struk lama
        removeArray(); 

        // 3. Looping Data
        for (int i = 0; i < model.getRowCount(); i++) {
            String noFaktur = model.getValueAt(i, 0).toString();
            String tanggal = model.getValueAt(i, 1).toString();
            String item = model.getValueAt(i, 2).toString();
            String qty = model.getValueAt(i, 3).toString();
            String harga = model.getValueAt(i, 4).toString();
            String jumlah = model.getValueAt(i, 5).toString();

            // Insert ke DB
            ps.setString(1, noFaktur);
            ps.setString(2, tanggal);
            ps.setString(3, item);
            ps.setString(4, qty);
            ps.setString(5, harga);
            ps.setString(6, jumlah);
            ps.executeUpdate();

            // Masukkan ke Array untuk Dicetak di Struk
            menuAry.add(item);
            qtyAry.add(qty);
            hargaAry.add(harga);
            jumlahAry.add(jumlah);
        }

        // 4. Pesan Sukses
        JOptionPane.showMessageDialog(null, "Transaksi Berhasil!");

        // --- PROSES CETAK STRUK THERMAL ---
        int confirm = JOptionPane.showConfirmDialog(null, "Cetak Struk Belanja?", "Cetak", JOptionPane.YES_NO_OPTION);
        
        if (confirm == 0) { 
            PrinterJob pj = PrinterJob.getPrinterJob();
            pj.setPrintable(new BillPrintable(), getPageFormat(pj));
            
            try {
                // Akan muncul dialog pilihan printer, PILIH PRINTER BLUETOOTH ANDA DISINI
                pj.print(); 
            } catch (PrinterException ex) {
                JOptionPane.showMessageDialog(null, "Gagal Mencetak: " + ex.getMessage());
            }
        }
        // ----------------------------------

        // 5. Reset Sistem
        removeArray();
        noFaktur();
        reset(); 

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btn_BayarActionPerformed

    private void txt_CariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CariKeyReleased
        // TODO add your handling code here:
        showDataItem();
    }//GEN-LAST:event_txt_CariKeyReleased

    private void txt_QtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_QtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_QtyActionPerformed

    private void tbl_MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_MenuMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbl_Menu.getModel();
        int selectedRow = tbl_Menu.getSelectedRow();
        String menu = model.getValueAt(selectedRow, 1).toString();
        String harga = model.getValueAt(selectedRow, 2).toString();
        int qty = 1; // Default quantity
        String message = "<html><b style='color:green; font-size:35px'>" + menu + "</b></html>";
        
        int confirm = JOptionPane.showConfirmDialog(null, message, "Pilih Menu", JOptionPane.YES_NO_OPTION);
        if (confirm == 0) {
        txt_Menu.setText(menu);
        txt_Harga.setText(harga);
        txt_Qty.setText(String.valueOf(qty));
        txt_Qty.requestFocus();
        txt_Cari.setText("");
        showDataItem();
        } else {
        txt_Cari.setText("");
        showDataItem();
        }
    }//GEN-LAST:event_tbl_MenuMouseClicked

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        // TODO add your handling code here:
        // 1. Validasi: Cek apakah ada input yang kosong
        if (txt_Menu.getText().equals("") || txt_Harga.getText().equals("") || txt_Qty.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Gagal menambahkan barang, data belum lengkap!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Proses Tambah Data (Hanya jalan jika lolos validasi di atas)
        DefaultTableModel model = (DefaultTableModel) tbl_Transaksi.getModel();

        String noFaktur = lbl_Faktur.getText(); 
        String tanggal = lbl_Tanggal.getText();
        String menu = txt_Menu.getText();
        String hargaTampil = txt_Harga.getText(); 
        String qty = txt_Qty.getText();

        try {
            // Bersihkan format harga (misal "15.000" jadi "15000")
            String hargaMurni = hargaTampil.replaceAll("[^0-9]", "");

            int hargaInt = Integer.parseInt(hargaMurni);
            int qtyInt = Integer.parseInt(qty);

            // Hitung total
            int jumlah = hargaInt * qtyInt;

            // Format hasil kali kembali ke format ribuan (Indonesia)
            NumberFormat kursIndo = NumberFormat.getIntegerInstance(new Locale("id", "ID"));
            String jumlahFormatted = kursIndo.format(jumlah);

            // Masukkan ke tabel
            model.addRow(new Object[]{noFaktur, tanggal, menu, qty, hargaTampil, jumlahFormatted});

        } catch (Exception e) {
            System.out.println("Error perhitungan: " + e.getMessage());
        }
        total();
        
        txt_Menu.setText("");
        txt_Harga.setText("");
        txt_Qty.setText("");
        txt_Cari.setText("");
        txt_Cari.requestFocus();
    }//GEN-LAST:event_btn_AddActionPerformed

    private void txt_TunaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TunaiKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume(); // Batalkan input jika bukan angka
        }
    }//GEN-LAST:event_txt_TunaiKeyTyped

    private void txt_TotalBayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TotalBayarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TotalBayarKeyReleased

    private void txt_TunaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TunaiKeyReleased
        // TODO add your handling code here:
        formatDesimal();
    }//GEN-LAST:event_txt_TunaiKeyReleased

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btn_ResetActionPerformed

    private void tbl_TransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_TransaksiMouseClicked
        // 1. Ambil Model Tabel
        DefaultTableModel model = (DefaultTableModel) tbl_Transaksi.getModel();

        // 2. Ambil Baris yang Diklik (Selected Row)
        int selectedRow = tbl_Transaksi.getSelectedRow();

        // 3. Validasi: Pastikan ada baris yang dipilih (Index tidak -1)
        if (selectedRow != -1) {
            model.removeRow(selectedRow);
            total();
        }
    }//GEN-LAST:event_tbl_TransaksiMouseClicked

    private void txt_QtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_QtyKeyPressed
        // Cek jika tombol yang ditekan adalah ENTER
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btn_AddActionPerformed(null);
        }
    }//GEN-LAST:event_txt_QtyKeyPressed

    private void txt_TunaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TunaiKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            btn_BayarActionPerformed(null);
        }
    }//GEN-LAST:event_txt_TunaiKeyPressed

    private void btn_TambahItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TambahItemActionPerformed
        // TODO add your handling code here:
        new Data_Item().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_TambahItemActionPerformed

    private void btn_DepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DepositActionPerformed
        // TODO add your handling code here:
        new Deposit().setVisible(true);
    }//GEN-LAST:event_btn_DepositActionPerformed

    private void btn_PengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PengeluaranActionPerformed
        // TODO add your handling code here:
        new Pengeluaran().setVisible(true);
    }//GEN-LAST:event_btn_PengeluaranActionPerformed

    private void btn_LaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LaporanActionPerformed
        // TODO add your handling code here:
        try {
        new Laporan().setVisible(true);
    } catch (Exception e) {
        // Ini akan memunculkan popup jika Laporan gagal dibuka
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal membuka Laporan: " + e.getMessage());
        e.printStackTrace(); // Cek tab Output di bawah NetBeans untuk detail error
    }
    }//GEN-LAST:event_btn_LaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Header;
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Bayar;
    private javax.swing.JButton btn_Deposit;
    private javax.swing.JButton btn_Laporan;
    private javax.swing.JButton btn_Pengeluaran;
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_TambahItem;
    private javax.swing.JPanel item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_Faktur;
    private javax.swing.JLabel lbl_Tanggal;
    private javax.swing.JTable tbl_Menu;
    private javax.swing.JTable tbl_Transaksi;
    private javax.swing.JPanel transaksi;
    private javax.swing.JTextField txt_Cari;
    private javax.swing.JTextField txt_Harga;
    private javax.swing.JTextField txt_Kembali;
    private javax.swing.JTextField txt_Menu;
    private javax.swing.JTextField txt_Qty;
    private javax.swing.JTextField txt_TotalBayar;
    private javax.swing.JTextField txt_Tunai;
    // End of variables declaration//GEN-END:variables

    private void showDataItem() {
        // 1. Inisialisasi Model Tabel
    DefaultTableModel model = (DefaultTableModel) tbl_Menu.getModel();
    model.setRowCount(0);
    
    try {
        // 3. Query Pencarian (Menggunakan INSTR)
        // Logika: Jika txt_cari kosong, INSTR akan tetap mengembalikan nilai > 0 (True), jadi semua data tampil.
        String sql = "SELECT * FROM tbl_dataitem WHERE INSTR(nama_item, ?) > 0";
        
        ps = conn.prepareStatement(sql);
        ps.setString(1, txt_Cari.getText()); // Mengambil kata kunci dari text field pencarian
        
        rs = ps.executeQuery();

        // 4. Looping Data
        while (rs.next()) {
            // Ambil data dari database
            // (Kolom 'No' tidak ditampilkan di tabel sesuai hasil akhir video, tapi bisa disesuaikan)
            String nama = rs.getString("nama_item");
            String kategori = rs.getString("kategori");
            int harga = rs.getInt("harga");
            
            // Format Harga ke Rupiah
            String hargaFormatted = angkakoma.format(harga);

            // Masukkan ke array Object (Sesuaikan urutan kolom tabel Anda)
            // Di video urutannya: Kategori, Nama Menu, Harga
            Object[] rowData = {kategori, nama, hargaFormatted};
            
            // Tambahkan baris ke model tabel
            model.addRow(rowData);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
}
    
    private void total() {
        int tot = 0; // Variabel penampung total

        // Looping sebanyak jumlah baris di tabel
        for (int i = 0; i < tbl_Transaksi.getRowCount(); i++) {

            // Ambil nilai dari kolom ke-5 (Index 5 = Kolom Jumlah)
            // Sesuaikan index ini dengan struktur tabel Anda (mulai dari 0)
            String jumlahStr = tbl_Transaksi.getValueAt(i, 5).toString();

            // Bersihkan format (Hapus titik/koma/Rp) agar jadi angka murni
            // Contoh: "30.000" -> "30000"
            String jumlahMurni = jumlahStr.replaceAll("[^0-9]", "");

            // Ubah ke integer dan tambahkan ke total
            int jumlahInt = Integer.parseInt(jumlahMurni);
            tot += jumlahInt;
        }
        java.text.NumberFormat kursIndo = java.text.NumberFormat.getIntegerInstance(new java.util.Locale("id", "ID"));
        txt_TotalBayar.setText(kursIndo.format(tot));
    }
    
    
    private void formatDesimal() {
        // A. SETTING FORMAT ANGKA (KOMA SEBAGAI PEMISAH RIBUAN)
        java.text.DecimalFormat dcf = new java.text.DecimalFormat("#,###,###");

        try {
            // 1. Validasi jika kolom tunai kosong
            if (txt_Tunai.getText().equals("")) {
                txt_Kembali.setText(""); // Kosongkan kembalian
                return;
            }

            // 2. Format Kolom Tunai (agar muncul koma saat ketik)
            // Hapus semua karakter selain angka agar bisa diformat ulang
            String tunaiBersih = txt_Tunai.getText().replaceAll("[^0-9]", "");
            double tunaiDouble = Double.parseDouble(tunaiBersih);

            // Set kembali teks dengan format baru (cegah error looping dengan validasi sederhana)
            // Catatan: Di video dia langsung set, tapi sebaiknya gunakan textfield 'Formatted' atau logika replace hati-hati.
            // Untuk sederhananya sesuai video:
            txt_Tunai.setText(dcf.format(tunaiDouble));

            // B. LOGIKA HITUNG KEMBALIAN

            // 3. Ambil data Total Bayar & Tunai (Hapus koma dulu biar jadi angka murni)
            // Pastikan txt_totalbayar tidak kosong
            String totalStr = txt_TotalBayar.getText().replaceAll("[^0-9]", "");
            String cashStr = txt_Tunai.getText().replaceAll("[^0-9]", "");

            int total = Integer.parseInt(totalStr);
            int cash = Integer.parseInt(cashStr);

            // 4. Hitung Selisih
            if (cash >= total) {
                int kembali = cash - total;
                // Tampilkan kembalian dengan format angka
                txt_Kembali.setText(dcf.format(kembali));
            } else {
                // Jika uang kurang, kosongkan kembalian
                txt_Kembali.setText("");
            }

        } catch (Exception e) {
            // Abaikan error parsing saat mengetik
        }
    }
    
    
    private void noFaktur() {
        try {
            // 1. Ambil nomor faktur tertinggi (terakhir) dari database
            String sql = "SELECT MAX(no_faktur) FROM tbl_penjualan";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            if (rs.next()) {
                String maxFaktur = rs.getString(1); // Ambil hasil query MAX

                // 2. Jika database masih kosong / belum ada transaksi
                if (maxFaktur == null) {
                    lbl_Faktur.setText("INV00001");
                } else {
                    // 3. Jika sudah ada data, ambil angkanya saja
                    // Misal: "INV00005" -> diambil "00005" (mulai index 3 karena "INV" ada 3 huruf)
                    long id = Long.parseLong(maxFaktur.substring(3));

                    // 4. Tambah angkanya dengan 1
                    id++;

                    // 5. Format ulang menjadi INV + 5 digit angka (00006)
                    // %05d artinya: format angka desimal dengan padding 0 di depan hingga 5 digit
                    String newFaktur = "INV" + String.format("%05d", id);

                    lbl_Faktur.setText(newFaktur);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Generate Nomor Faktur: " + e.getMessage());
        }
    }
    
    
    private void tampilTanggal() {
        // 1. Ambil Waktu Saat Ini
        Date tgl = new Date();

        // 2. Tentukan Format Tanggal
        // "dd" = Tanggal, "MM" = Bulan, "yyyy" = Tahun
        // Contoh format: "dd-MM-yyyy" hasilnya "30-09-2024"
        SimpleDateFormat formatTanggal = new SimpleDateFormat("dd-MM-yyyy");

        // Jika ingin format garis miring: new SimpleDateFormat("dd/MM/yyyy");

        // 3. Ubah (Format) Tanggal menjadi String
        String tanggalSekarang = formatTanggal.format(tgl);

        // 4. Set ke Label
        lbl_Tanggal.setText(tanggalSekarang);
    }
    
    
    private void reset() {
        // 1. Kosongkan semua JTextField
        txt_Menu.setText("");
        txt_Harga.setText("");
        txt_Qty.setText("");
        txt_TotalBayar.setText("");
        txt_Tunai.setText("");
        txt_Kembali.setText("");

        // 2. Kosongkan JTable Transaksi (Keranjang Belanja)
        DefaultTableModel model = (DefaultTableModel) tbl_Transaksi.getModel();
        model.setRowCount(0); // Menghapus semua baris di tabel
    }
    
    
    private void removeArray() {
        menuAry.clear();
        qtyAry.clear();
        hargaAry.clear();
        jumlahAry.clear();
    }
    
    public PageFormat getPageFormat(PrinterJob pj) {
        PageFormat pf = pj.defaultPage();
        Paper paper = pf.getPaper();

        // --- SETTING UKURAN KERTAS (58mm) ---
        // Lebar 58mm = sekitar 160-165 points
        double width = 164d; 

        // Tinggi Kertas Dinamis
        // Header (logo/judul) + Footer (total/ucapan) + (Jml Barang * Tinggi Baris)
        double headerHeight = 100d; 
        double footerHeight = 100d;
        double itemHeight = 20d; // Jarak antar barang

        double height = headerHeight + (menuAry.size() * itemHeight) + footerHeight;

        paper.setSize(width, height);
        paper.setImageableArea(0, 0, width, height); // Margin 0 agar muat banyak

        pf.setOrientation(PageFormat.PORTRAIT);
        pf.setPaper(paper);

        return pf;
    }
    
    public class BillPrintable implements Printable {
        public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
            if (pageIndex > 0) return NO_SUCH_PAGE;

            Graphics2D g2d = (Graphics2D) graphics;
            g2d.translate(pageFormat.getImageableX(), pageFormat.getImageableY());

            // Font: Monospaced sangat penting agar kolom rapi
            Font fontRegular = new Font("Monospaced", Font.PLAIN, 8);
            Font fontBold = new Font("Monospaced", Font.BOLD, 10);

            int y = 15; // Posisi Y awal (margin atas)

            // --- HEADER ---
            g2d.setFont(fontBold);
            g2d.drawString("KEDAI KOPI NIKMAT", 15, y); 
            y += 10;
            g2d.setFont(fontRegular);
            g2d.drawString("Jl. Majapahit No.20", 10, y); 
            y += 20;

            g2d.drawString("Faktur: " + lbl_Faktur.getText(), 5, y);
            y += 10;
            g2d.drawString("Tgl   : " + lbl_Tanggal.getText(), 5, y);
            y += 10;
            g2d.drawString("--------------------------------", 5, y);
            y += 10;

            // --- ITEM BELANJA ---
            for (int i = 0; i < menuAry.size(); i++) {
                String namaItem = menuAry.get(i);
                String qty = qtyAry.get(i);
                String harga = hargaAry.get(i);
                String subtotal = jumlahAry.get(i);

                // Baris 1: Nama Barang
                g2d.drawString(namaItem, 5, y);
                y += 10;

                // Baris 2: Qty x Harga = Total (Menjorok ke kanan)
                // Contoh: 2 x 15.000 = 30.000
                String rincian = qty + " x " + harga;
                g2d.drawString(rincian, 5, y);

                // Total ditaruh di sebelah kanan (Manual alignment)
                // Trik sederhana meratakan kanan untuk struk kecil
                int panjangString = subtotal.length() * 5; // Estimasi lebar text
                g2d.drawString(subtotal, 140 - panjangString, y); 

                y += 15; // Jarak antar item
            }

            g2d.drawString("--------------------------------", 5, y);
            y += 10;

            // --- TOTAL & PEMBAYARAN ---
            g2d.setFont(fontBold);
            g2d.drawString("TOTAL   : " + txt_TotalBayar.getText(), 5, y);
            y += 10;
            g2d.setFont(fontRegular);
            g2d.drawString("TUNAI   : " + txt_Tunai.getText(), 5, y);
            y += 10;
            g2d.drawString("KEMBALI : " + txt_Kembali.getText(), 5, y);
            y += 20;

            // --- FOOTER ---
            g2d.drawString("* TERIMA KASIH *", 35, y);
            y += 10;
            g2d.drawString("Barang yang dibeli", 25, y);
            y += 10;
            g2d.drawString("tidak dapat ditukar", 20, y);

            return PAGE_EXISTS;
        }
    }
}
