/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import java.sql.*;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khoirul umam
 */
public class Data_Item extends javax.swing.JFrame {

    public Statement st;
    public PreparedStatement ps;
    public ResultSet rs;
    // Pastikan Class Config.Koneksi benar ada di project Anda
    Connection conn = Config.Koneksi.koneksiDB(); 
    
    public Data_Item() {
        initComponents();
        showdata();
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_Nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Harga = new javax.swing.JTextField();
        cmb_Kategori = new javax.swing.JComboBox<>();
        btn_Hapus = new javax.swing.JButton();
        btn_Reset = new javax.swing.JButton();
        btn_Simpan = new javax.swing.JButton();
        btn_Kembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Item = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel2.setText("Nama Item");

        jLabel3.setText("Kategori");

        jLabel4.setText("Harga");

        txt_Harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HargaActionPerformed(evt);
            }
        });
        txt_Harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_HargaKeyReleased(evt);
            }
        });

        cmb_Kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak ada", "Makanan", "Minuman" }));

        btn_Hapus.setText("Hapus");
        btn_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HapusActionPerformed(evt);
            }
        });

        btn_Reset.setText("Reset");
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });

        btn_Simpan.setText("Simpan");
        btn_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SimpanActionPerformed(evt);
            }
        });

        btn_Kembali.setText("Kembali");
        btn_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Harga)
                    .addComponent(txt_Nama)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_Hapus)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Simpan)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Reset)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Kembali)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cmb_Kategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmb_Kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Hapus)
                    .addComponent(btn_Reset)
                    .addComponent(btn_Simpan)
                    .addComponent(btn_Kembali))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(0, 51, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("DATA ITEM");

        tbl_Item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama Item", "Kategori", "Harga"
            }
        ));
        tbl_Item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Item);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void formatRupiah() {
        if (!txt_Harga.getText().equals("")) {
            // Hapus semua karakter kecuali angka (0-9)
            String Replace = txt_Harga.getText().replaceAll("[^0-9]", ""); 
            double FormatRp = Double.parseDouble(Replace);
            DecimalFormat dcf = new DecimalFormat("#,###,###");
            txt_Harga.setText(dcf.format(FormatRp));
        }
}
    private void btn_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SimpanActionPerformed
        // 1. Validasi Input Kosong
        if (txt_Nama.getText().equals("") || txt_Harga.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Data Yang Akan di Masukkan Belum Lengkap", "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            st = conn.createStatement();
            
            // Bersihkan format (hapus koma/titik) sebelum disimpan ke database
            String hargaMurni = txt_Harga.getText().replaceAll("[^\\d]", "");

            if (btn_Simpan.getText().equals("Simpan")) {
                // --- INSERT DATA ---
                String find = "SELECT * FROM tbl_dataitem WHERE nama_item='" + txt_Nama.getText() + "'";
                rs = st.executeQuery(find);
                
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Menu Sudah Pernah di Masukkan, Silahkan Masukan Menu Lain", "Validasi", JOptionPane.WARNING_MESSAGE);
                } else {
                    String nama = txt_Nama.getText();
                    String kategori = cmb_Kategori.getItemAt(cmb_Kategori.getSelectedIndex());
                    
                    String sql = "INSERT INTO tbl_dataitem (nama_item, kategori, harga) VALUES (?, ?, ?)";
                    
                    ps = conn.prepareStatement(sql);
                    ps.setString(1, nama);
                    ps.setString(2, kategori);
                    ps.setString(3, hargaMurni); // Gunakan harga yang sudah dibersihkan
                    
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan", "Input Data", JOptionPane.INFORMATION_MESSAGE);
                    showdata();
                    reset();
                }
            } else {
                // Ambil nama item dari TABEL (Nama LAMA sebelum diedit)
                int selectedRow = tbl_Item.getSelectedRow();
                String namaLama = tbl_Item.getValueAt(selectedRow, 1).toString();

                // Query Update: Ubah data DI MANA nama_item = namaLama
                String updateSql = "UPDATE tbl_dataitem SET nama_item = ?, kategori = ?, harga = ? WHERE nama_item = ?";

                ps = conn.prepareStatement(updateSql);
                ps.setString(1, txt_Nama.getText()); // Nama Baru
                ps.setString(2, cmb_Kategori.getItemAt(cmb_Kategori.getSelectedIndex()).toString());
                ps.setString(3, hargaMurni);
                ps.setString(4, namaLama); // Where Nama Lama

                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data berhasil di-Update");

                showdata(); 
                reset();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_SimpanActionPerformed

    private void tbl_ItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ItemMouseClicked
        DefaultTableModel model = (DefaultTableModel) tbl_Item.getModel();
    int selectedRow = tbl_Item.getSelectedRow();

    txt_Nama.setText(model.getValueAt(selectedRow, 1).toString());

    // Set ComboBox
    String colomKat = model.getValueAt(selectedRow, 2).toString();
    for (int i = 0; i < cmb_Kategori.getItemCount(); i++) {
        if (cmb_Kategori.getItemAt(i).toString().equalsIgnoreCase(colomKat)) {
            cmb_Kategori.setSelectedIndex(i);
        }
    }

    // --- PERBAIKAN UTAMA ADA DI SINI ---
    String hargaTabel = model.getValueAt(selectedRow, 3).toString(); // Contoh: "Rp15.000,00"
    
    // 1. Pisahkan dulu bagian rupiah dengan sen (koma)
    String[] pisah = hargaTabel.split(","); // Memisahkan "Rp15.000" dan "00"
    
    // 2. Ambil hanya bagian depannya saja (Rp15.000)
    String hargaUtama = pisah[0]; 
    
    // 3. Bersihkan simbol Rp dan titik
    String hargaBersih = hargaUtama.replaceAll("[^0-9]", ""); // Hasil: "15000"
    
    txt_Harga.setText(hargaBersih);
    // ------------------------------------

    btn_Simpan.setText("Update");
    formatRupiah(); // Format ulang agar jadi "15.000" di textfield
    }//GEN-LAST:event_tbl_ItemMouseClicked

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
        reset();
    }//GEN-LAST:event_btn_ResetActionPerformed

    private void btn_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HapusActionPerformed
        try {
        if (txt_Nama.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Silakan pilih data yang akan dihapus", "Validasi", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah Anda ingin menghapus data ini?", "Hapus Data", JOptionPane.YES_NO_OPTION);

        if (konfirmasi == 0) { 
            // PERUBAHAN DI SINI:
            // Kita hapus berdasarkan NAMA ITEM (Kolom indeks 1), bukan Nomor
            DefaultTableModel model = (DefaultTableModel) tbl_Item.getModel();
            int selectedRow = tbl_Item.getSelectedRow();
            
            // Ambil Nama Item dari tabel (Kolom ke-1)
            String namaItem = model.getValueAt(selectedRow, 1).toString();

            // Query Delete menggunakan WHERE nama_item
            String sql = "DELETE FROM tbl_dataitem WHERE nama_item = ?";
            ps = conn.prepareStatement(sql);
            ps.setString(1, namaItem); // Set parameter berdasarkan nama
            ps.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");

            showdata(); // Refresh tabel
            reset();    
        } else {
            reset(); 
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_btn_HapusActionPerformed

    private void txt_HargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HargaActionPerformed
        
    }//GEN-LAST:event_txt_HargaActionPerformed

    private void txt_HargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_HargaKeyReleased
        formatRupiah();
    }//GEN-LAST:event_txt_HargaKeyReleased

    private void btn_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KembaliActionPerformed
        // TODO add your handling code here:
        new Beranda().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_KembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_Item().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Hapus;
    private javax.swing.JButton btn_Kembali;
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_Simpan;
    private javax.swing.JComboBox<String> cmb_Kategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Item;
    private javax.swing.JTextField txt_Harga;
    private javax.swing.JTextField txt_Nama;
    // End of variables declaration//GEN-END:variables

    private void showdata() {
        DefaultTableModel model = (DefaultTableModel) tbl_Item.getModel();
        model.setRowCount(0);

        // Setup Format Rupiah (Opsional, sesuai kode sebelumnya)
        java.text.NumberFormat kursIndo = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id", "ID"));
        kursIndo.setMaximumFractionDigits(0); 

        try {
            String sql = "SELECT * FROM tbl_dataitem";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();

            // BUAT VARIABEL NO URUT BARU DI SINI
            int noUrut = 1; 

            while (rs.next()) {
                // Kita tidak pakai rs.getInt("No") untuk tampilan
                String nama = rs.getString("nama_item");
                String kategori = rs.getString("kategori");
                int harga = rs.getInt("harga");

                // Format Harga
                String hargaFormatted = kursIndo.format(harga);

                // Masukkan noUrut ke kolom pertama, lalu noUrut ditambah 1 (noUrut++)
                Object[] rowData = {noUrut++, nama, kategori, hargaFormatted};
                model.addRow(rowData);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void reset() {
        txt_Nama.setText("");
        txt_Harga.setText("");
        cmb_Kategori.setSelectedIndex(0); 
        btn_Simpan.setText("Simpan"); 
    }
}
