/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Form;

import java.sql.*;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khoirul umam
 */
public class Laporan extends javax.swing.JFrame {
    
    Connection conn = Config.Koneksi.koneksiDB();
    PreparedStatement ps;
    ResultSet rs;
    NumberFormat kursIndo = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
    
    public Laporan() {
        initComponents();
        tampilData();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    private void tampilData() {
        DefaultTableModel model = (DefaultTableModel) tbl_Laporan.getModel();
        model.setRowCount(0); // Reset tabel

        double totalPendapatan = 0;

        try {
            // Query mengambil semua data dari tbl_penjualan urut berdasarkan faktur terbaru
            String sql = "SELECT * FROM tbl_penjualan ORDER BY no_faktur DESC";
            
            // Logika Pencarian (Jika txt_Cari tidak kosong)
            if (!txt_Cari.getText().isEmpty()) {
                sql = "SELECT * FROM tbl_penjualan WHERE no_faktur LIKE '%" + txt_Cari.getText() + "%' "
                        + "OR tanggal LIKE '%" + txt_Cari.getText() + "%' "
                        + "OR item LIKE '%" + txt_Cari.getText() + "%'";
            }

            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();

            while (rs.next()) {
                String faktur = rs.getString("no_faktur");
                String tgl = rs.getString("tanggal");
                String item = rs.getString("item");
                String qty = rs.getString("qty");
                
                // Konversi harga & jumlah dari String (di DB) ke Double/Int agar bisa diformat
                double harga = Double.parseDouble(rs.getString("harga").replaceAll("[^0-9]", ""));
                double subtotal = Double.parseDouble(rs.getString("jumlah").replaceAll("[^0-9]", ""));

                // Tambahkan ke Total Pendapatan
                totalPendapatan += subtotal;

                // Masukkan ke Tabel
                Object[] data = {
                    faktur,
                    tgl,
                    item,
                    qty,
                    kursIndo.format(harga),
                    kursIndo.format(subtotal)
                };
                model.addRow(data);
            }
            
            // Set Text Total Pendapatan di bawah
            txt_TotalPendapatan.setText(kursIndo.format(totalPendapatan));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Tampil Data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_Cari = new javax.swing.JTextField();
        btn_Cari = new javax.swing.JButton();
        btn_Refresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Laporan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_TotalPendapatan = new javax.swing.JTextField();
        btn_Cetak = new javax.swing.JButton();
        btn_Tutup = new javax.swing.JButton();

        setForeground(java.awt.Color.yellow);
        setTitle("LAPORAN PENJUALAN");

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setToolTipText("");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cari (Faktur/Tanggal):");

        txt_Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CariActionPerformed(evt);
            }
        });
        txt_Cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_CariKeyReleased(evt);
            }
        });

        btn_Cari.setText("Cari");
        btn_Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CariActionPerformed(evt);
            }
        });

        btn_Refresh.setText("Refresh");
        btn_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RefreshActionPerformed(evt);
            }
        });

        tbl_Laporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Faktur", "Tanggal", "Item", "Quantity", "Harga", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tbl_Laporan);

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Pendapatan");

        txt_TotalPendapatan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_TotalPendapatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TotalPendapatanActionPerformed(evt);
            }
        });

        btn_Cetak.setText("Cetak Laporan / PDF");
        btn_Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CetakActionPerformed(evt);
            }
        });

        btn_Tutup.setText("Tutup");
        btn_Tutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Cetak)
                        .addGap(65, 65, 65)
                        .addComponent(btn_Tutup, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_TotalPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(59, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_TotalPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cetak)
                    .addComponent(btn_Tutup))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Cari)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Cari)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Refresh)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Cari)
                    .addComponent(btn_Refresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CariActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_CariActionPerformed

    private void btn_CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CariActionPerformed
        // TODO add your handling code here:
        tampilData();
    }//GEN-LAST:event_btn_CariActionPerformed

    private void btn_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RefreshActionPerformed
        // TODO add your handling code here:
        txt_Cari.setText(""); // Kosongkan kolom pencarian
        tampilData();
    }//GEN-LAST:event_btn_RefreshActionPerformed

    private void btn_TutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TutupActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_TutupActionPerformed

    private void txt_CariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CariKeyReleased
        // TODO add your handling code here:
        tampilData();
    }//GEN-LAST:event_txt_CariKeyReleased

    private void btn_CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CetakActionPerformed
        // TODO add your handling code here:
        try {
            // Fitur bawaan JTable untuk mencetak (Simple Print)
            // Mode FIT_WIDTH agar tabel muat di satu kertas
            boolean complete = tbl_Laporan.print(javax.swing.JTable.PrintMode.FIT_WIDTH, 
                    new java.text.MessageFormat("Laporan Penjualan Kedai Kopi"), 
                    new java.text.MessageFormat("Halaman {0}"));
            
            if (complete) {
                JOptionPane.showMessageDialog(null, "Cetak Selesai");
            } else {
                JOptionPane.showMessageDialog(null, "Cetak Dibatalkan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Mencetak: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_CetakActionPerformed

    private void txt_TotalPendapatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TotalPendapatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TotalPendapatanActionPerformed
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cari;
    private javax.swing.JButton btn_Cetak;
    private javax.swing.JButton btn_Refresh;
    private javax.swing.JButton btn_Tutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Laporan;
    private javax.swing.JTextField txt_Cari;
    private javax.swing.JTextField txt_TotalPendapatan;
    // End of variables declaration//GEN-END:variables
    
    
}
